### ISSUE TITLE
Windows 10 Touch Chrome 70, the touch feature is disabled

### ISSUE THREAD

**Issue by florianduros** [dimsemenov/PhotoSwipe#1579]
Hello,

With chrome 70 in windows 10, the touch check in `src/js/framework-bridge.js` doesn't work as expected:

```javascript
features.touch = 'ontouchstart' in window;
```
The touch verification can be done in this way:

```javascript
features.touch = 'ontouchstart' in document.documentElement || navigator.maxTouchPoints > 0
```
It covers most of the recent browsers in touch mode

**Comment by theenoahmason** [comment]
Can confirm, Photoswipe not swiping on all windows 10 touch laptops, surface devices, and other windows 10 tablets in latest chrome.

**Comment by GDovis** [comment]
I have the same problem. Does not work on Chrome and Opera browsers in Windows10 on ultrabook with touchscreen. In other browsers works fine.
Tried your solution - it fixed sliding problem, but new problem appeared.
Now when I click to outside of image with touchscreen - nothing happens. If I double click - image "Zoom" function gets triggered. Before this fix clicking outside of image once made "Exit" (same as ESC button on keyboard) function.
Is it possible to fix this too? Thanks.

**Comment by theenoahmason** [comment]
@GDovis PhotoSwipe never closed on click.

**Comment by GDovis** [comment]
Attaching screenshot it works when you pres out of frame (picture) and it worked before this fix: http://prntscr.com/luzpa9
You cant test it here too: http://photoswipe.com/

After this fix scroll works on all browsers with touchscreen but clicking outside of frame zooms to picture instead of closing it. It acts the same as you press on actual picture (zoom happens) but outside of frame it closes by default, not zooms.

**Comment by GDovis** [comment]
So is there any normal fix to this? Other gallery plugins has it fixed by default. I'm using "dream-theme the7" theme which includes this gallery plugin so I'm stuck with this gallery. The7 theme support forwarded me here.
I also wrote letter to this gallery plugin developer and got no respond.
Is this gallery plugin gets support by the one who made it?..

**Comment by florianduros** [comment]
I still have the issue with the last release 4.1.3. The touch feature is still disabled.

**Comment by GDovis** [comment]
Greetings, bug is fixed but partly. Tested on windows 10 multi-touch Lenovo ultrabook with latest updates your demo from here: https://photoswipe.com
On Chrome and on Edge now it works.
But on Internet explorer (v11.678) touch-slide photos option does not work.

Interestingly I use your plugn trough Theme: https://the7.io/
And they gave me solution before your bug was fixed:

main.min.js:
replace
d.touch="ontouchstart"in window
with
d.touch="ontouchstart"in document.documentElement||navigator.maxTouchPoints>0

And with this fix even in Internet explorer multi-touch works.
so maybe you can update your code too so it will be fixed in IE (now its only fixed in Chrome and Edge)
