### ISSUE TITLE
v5-beta - Not clear how to install and import Photoswipe

### ISSUE THREAD

**Issue by dangelion** [dimsemenov/PhotoSwipe#1763]
Hi @dimsemenov , as a premise, thanks for your incredible work! Really.

I work in a classic Webpack environment so I install libraries launching:

`npm install swiper`

then I import libraries in my `app.js` like:

`import Swiper, {Navigation} from 'swiper';`

and CSS in my `app.scss` like:

`@import "~swiper/swiper";`

getting automatically it from the `node_modules` folder.

Note: I can't put an absolute path as show in docs because I install it via npm:

`pswpModule: '/v5/photoswipe/photoswipe.esm.js'  //<== Can't do something like https://mysite.com/photoswipe.esm.js`

If only solution is import all modules at start that's not a problem to me, but I don't understand how to do that.

Any help is really welcome cause I'm currently stuck to use it :(
Thanks

**Comment by dimsemenov** [comment]
You can install the beta like this `npm i--save git://github.com/dimsemenov/photoswipe#v5-beta`.

Then you'll be able to do:

```js
import PhotoSwipeLightbox from 'photoswipe/dist/photoswipe-lightbox.esm.js';
const options = {
  gallerySelector: '#my-gallery',
  pswpModule: 'https://example.com/photoswipe.esm.js'
};
const lightbox = new PhotoSwipeLightbox(options);
lightbox.init();
```

and import CSS with something like `import 'photoswipe/dist/photoswipe.css'`.

Please note that non-dynamic import of `pswpModule` isn't supported yet, but it's something that I or some contributor will implement. The code is here https://github.com/dimsemenov/PhotoSwipe/blob/v5-beta/src/js/lightbox/lightbox.js#L146 if you got some ideas on how to improve.

For now, if you use something like webpack - you may create multiple outputs, so your `pswpModule`. The path to pswpModule is `photoswipe/dist/photoswipe.esm.js`.

**Comment by dangelion** [comment]
Yes @dimsemenov 
already tried exactly what you suggest, but when I click an image I get error in console

```
Uncaught (in promise) Error: Cannot find module 'http://localhost:3000/wp-content/themes/mytheme/public/photoswipe-v5/dist/photoswipe.esm.min.js'
    at app.js?id=6d8dbee816224d2b6c2a:208
```

**Comment by dimsemenov** [comment]
It seems the error is added by the webpack when `photoswipe-lightbox.esm.js` is getting transpiled, since webpack is trying to override the default behavior of `import()`.

Changing `import(module);` to `import(/* webpackIgnore: true */ module);` does help, but it doesn't look like an ideal fix as other bundlers might have a similar issue.

I'm not sure what to do with it yet and how to make bundlers ignore dynamic import (aside from completely disabling the feature). possibly with polyfill https://github.com/GoogleChromeLabs/dynamic-import-polyfill

**Comment by dangelion** [comment]
Thanks @dimsemenov What should be the correct syntax to import Photoswipe with `import()`. Tried various but without luck:

```
import('photoswipe/dist/photoswipe-lightbox.esm.js');
import(PhotoSwipeLightbox from 'photoswipe/dist/photoswipe-lightbox.esm.js');
import(PhotoSwipeLightbox);
```

**Comment by dimsemenov** [comment]
should now be fixed by https://github.com/dimsemenov/PhotoSwipe/pull/1764#issuecomment-867453153 , so closing.

**Comment by dangelion** [comment]
@dimsemenov Almost there! There's a Warning while building, check here https://github.com/dimsemenov/PhotoSwipe/pull/1764#issuecomment-868279751

**Comment by multipliedtwice** [comment]
@dimsemenov not solved I think. In sveltekit breaks dev right away.
